using System.Net;
using System.Net.NetworkInformation;

internal sealed class ReceiveView : UserControl
{
    readonly DesktopReceiver receiver=new();readonly string preferences;
    readonly Label state=new(){Text="Preparando recebimento…",Dock=DockStyle.Fill,ForeColor=Palette.Muted};
    readonly Label destination=new(){Dock=DockStyle.Fill,ForeColor=Palette.Muted};readonly TransferProgress progress=new(){Dock=DockStyle.Fill,Visible=false};
    string folder;int receiverPort=DesktopReceiver.Port;CancellationTokenSource? session;bool ready,closing;public bool Busy {get;private set;}public event Action<bool>? ListeningChanged;
    public ReceiveView(string preferences)
    {
        this.preferences=preferences;folder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"Downloads","DropLocal");try{string saved=File.ReadAllText(Path.Combine(preferences,"receive-folder.txt")).Trim();if(Path.IsPathFullyQualified(saved))folder=saved;}catch(IOException){}catch(UnauthorizedAccessException){}
        BackColor=Palette.Background;var card=new Card{Dock=DockStyle.Fill,Margin=new Padding(0,0,0,12)};var grid=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=3,BackColor=Palette.Panel};grid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));grid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,140));grid.RowStyles.Add(new RowStyle(SizeType.Absolute,24));grid.RowStyles.Add(new RowStyle(SizeType.Percent,100));grid.RowStyles.Add(new RowStyle(SizeType.Absolute,10));grid.Controls.Add(destination,0,0);grid.Controls.Add(state,0,1);var open=new ActionButton{Text="Abrir recebidos",Dock=DockStyle.Fill};open.Click+=(_,_)=>{if(Directory.Exists(folder))System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(folder){UseShellExecute=true});};grid.Controls.Add(open,1,1);grid.Controls.Add(progress,0,2);grid.SetColumnSpan(progress,2);card.Controls.Add(grid);Controls.Add(card);destination.Text="Salvar em: "+folder;
    }
    internal PairSession Pairing=>receiver.Session;internal string DiscoveryToken=>receiver.DiscoveryToken;internal string VerificationCode=>receiver.Code;internal bool IsListening=>ready;internal bool IsRunning=>session!=null;
    internal void StartForCheck(string directory,int port=DesktopReceiver.Port){receiverPort=port;folder=directory;destination.Text="Salvar em: "+directory;StartDefault();}
    internal void Preview(){destination.Text="Salvar em: Downloads\\DropLocal";state.Text="Pronto para receber · você confirma cada pedido.";}
    internal async void StartDefault()
    {
        if(session!=null||closing)return;var current=new CancellationTokenSource();session=current;
        try{await receiver.RunAsync(folder,Approve,(done,total,name)=>Ui(()=>{Busy=true;progress.Visible=true;progress.Value=total==0?100:(int)(done*100.0/total);state.Text=$"Recebendo · {progress.Value}%\n{name}";}),message=>Ui(()=>{Busy=message.StartsWith("Pedido recebido");state.Text=message;if(message.StartsWith("Receptor disponível")){ready=true;ListeningChanged?.Invoke(true);}if(message.StartsWith("Pedido recebido")){progress.Visible=false;progress.Value=0;}if(message.StartsWith("Transferência concluída")){progress.Visible=true;progress.Value=100;}}),(_,_)=>{},current.Token,receiverPort);}
        catch(OperationCanceledException){if(!closing)state.Text="Recebimento pausado.";}catch(Exception e){if(!closing)state.Text="Não foi possível receber: "+e.Message;}
        finally{ready=false;Busy=false;session=null;current.Dispose();receiver.Reset();if(!closing)ListeningChanged?.Invoke(false);}
    }
    public void Stop(){ready=false;session?.Cancel();}
    internal async Task ShowSettings(Form owner)
    {
        if(Busy){MessageBox.Show(owner,"Aguarde terminar o recebimento para alterar a pasta.","Drop Local");return;}
        using var dialog=new Form{Text="Drop Local — configurações",Icon=AppIdentity.Icon,BackColor=Palette.Background,ForeColor=Palette.Text,Font=Font,ClientSize=new Size(570,540),StartPosition=FormStartPosition.CenterParent,MinimizeBox=false,MaximizeBox=false};
        var body=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true,Padding=new Padding(18)};dialog.Controls.Add(body);var path=new Label{Text="Arquivos recebidos são salvos em:\n"+folder,Width=510,Height=54,ForeColor=Palette.Text};body.Controls.Add(path);
        var choose=new ActionButton{Text="Alterar pasta",Width=510,Height=40};body.Controls.Add(choose);choose.Click+=async(_,_)=>{if(Busy)return;Stop();for(int i=0;i<100&&IsRunning;i++)await Task.Delay(20);using var picker=new FolderBrowserDialog{SelectedPath=folder};if(picker.ShowDialog(dialog)==DialogResult.OK){folder=picker.SelectedPath;Directory.CreateDirectory(preferences);File.WriteAllText(Path.Combine(preferences,"receive-folder.txt"),folder);destination.Text="Salvar em: "+folder;path.Text="Arquivos recebidos são salvos em:\n"+folder;}StartDefault();};
        var manual=new ActionButton{Text="Conexão manual (IP e código)",Width=510,Height=40};body.Controls.Add(manual);var advanced=new FlowLayoutPanel{FlowDirection=FlowDirection.TopDown,WrapContents=false,Width=510,Height=610,Visible=false};body.Controls.Add(advanced);manual.Click+=(_,_)=>advanced.Visible=!advanced.Visible;
        string ips=string.Join(" / ",NetworkInterface.GetAllNetworkInterfaces().Where(n=>n.OperationalStatus==OperationalStatus.Up).SelectMany(n=>n.GetIPProperties().UnicastAddresses).Select(a=>a.Address).Where(a=>a.AddressFamily==System.Net.Sockets.AddressFamily.InterNetwork&&!IPAddress.IsLoopback(a)));
        advanced.Controls.Add(new Label{Text="Meu IP: "+ips+"\nMeu código: "+receiver.Code,Width=500,Height=48,ForeColor=Palette.Accent});var ipBox=new TextBox{Width=500,PlaceholderText="IP do outro aparelho"};var codeBox=new TextBox{Width=500,PlaceholderText="Código de oito dígitos",MaxLength=8};var type=new ComboBox{Width=500,DropDownStyle=ComboBoxStyle.DropDownList};type.Items.AddRange(new object[]{"Windows","Android"});type.SelectedIndex=0;advanced.Controls.Add(ipBox);advanced.Controls.Add(codeBox);advanced.Controls.Add(type);var pair=new ActionButton{Text="Conectar manualmente",Width=500,Height=40};advanced.Controls.Add(pair);pair.Click+=async(_,_)=>{if(!IPAddress.TryParse(ipBox.Text.Trim(),out var ip)||codeBox.Text.Length!=8){MessageBox.Show(dialog,"Informe IP e código do outro aparelho.");return;}pair.Enabled=false;using var deadline=new CancellationTokenSource(TimeSpan.FromSeconds(130));try{await receiver.Session.ConnectAsync(ip,type.SelectedIndex==0?45833:45832,codeBox.Text,45833,deadline.Token);MessageBox.Show(dialog,"Conectado. Você pode enviar pela conexão manual ou usar a lista automática.");}catch(Exception e){MessageBox.Show(dialog,e.Message);}finally{pair.Enabled=true;}};
        var send=new ActionButton{Text="Enviar pela conexão manual",Width=500,Height=40};advanced.Controls.Add(send);send.Click+=async(_,_)=>{if(receiver.Session.Peer is not {} peer){MessageBox.Show(dialog,"Conecte manualmente primeiro.");return;}using var picker=new OpenFileDialog{Multiselect=true,Title="Escolha os arquivos"};if(picker.ShowDialog(dialog)!=DialogResult.OK)return;send.Enabled=false;using var deadline=new CancellationTokenSource(TimeSpan.FromMinutes(5));try{await LocalTransfer.SendAsync(peer.Address,peer.SendToken,picker.FileNames,(_,_,_)=>{},message=>Ui(()=>send.Text=message),deadline.Token,peer.Port,2);MessageBox.Show(dialog,"Envio concluído.");}catch(Exception e){MessageBox.Show(dialog,e.Message);}finally{send.Enabled=true;send.Text="Enviar pela conexão manual";}};
        string? qrIp=ips.Split(" / ",StringSplitOptions.RemoveEmptyEntries).FirstOrDefault();if(qrIp!=null){var matrix=PairQr.Encode($"droplocal://pair?ip={qrIp}&port=45833&token={receiver.Code}");using var qr=new Bitmap(225,225);using(var paint=Graphics.FromImage(qr)){paint.Clear(Color.White);for(int y=0;y<37;y++)for(int x=0;x<37;x++)if(matrix[y,x])paint.FillRectangle(Brushes.Black,(x+4)*5,(y+4)*5,5,5);}advanced.Controls.Add(new PictureBox{Image=(Bitmap)qr.Clone(),Width=225,Height=225});}
        dialog.ShowDialog(owner);await Task.CompletedTask;
    }
    void Ui(Action action){if(closing||IsDisposed)return;if(InvokeRequired){try{BeginInvoke(()=>{if(!closing&&!IsDisposed)action();});}catch(InvalidOperationException)when(closing||IsDisposed){}}else action();}
    Task<bool> Approve(string message)
    {
        var result=new TaskCompletionSource<bool>();Ui(()=>{if(FindForm() is not Form owner){result.TrySetResult(false);return;}if(owner.WindowState==FormWindowState.Minimized)owner.WindowState=FormWindowState.Normal;owner.Activate();using var dialog=new Form{Text="Drop Local — autorização",Icon=AppIdentity.Icon,BackColor=Palette.Background,ForeColor=Palette.Text,ClientSize=new Size(540,420),StartPosition=FormStartPosition.CenterParent,MinimizeBox=false,MaximizeBox=false};var layout=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(18),ColumnCount=2,RowCount=2};layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,52));dialog.Controls.Add(layout);var details=new TextBox{Text=message,Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Vertical,Dock=DockStyle.Fill,BackColor=Palette.Field,ForeColor=Palette.Text,Font=new Font("Segoe UI",10),BorderStyle=BorderStyle.None};layout.Controls.Add(details,0,0);layout.SetColumnSpan(details,2);var no=new ActionButton{Text="Recusar",Danger=true,Dock=DockStyle.Fill,DialogResult=DialogResult.No};var yes=new ActionButton{Text="Aceitar",Primary=true,Dock=DockStyle.Fill,DialogResult=DialogResult.Yes};layout.Controls.Add(no,0,1);layout.Controls.Add(yes,1,1);dialog.AcceptButton=yes;dialog.CancelButton=no;using var timer=new System.Windows.Forms.Timer{Interval=120000};timer.Tick+=(_,_)=>{dialog.DialogResult=DialogResult.No;dialog.Close();};timer.Start();result.TrySetResult(dialog.ShowDialog(owner)==DialogResult.Yes);});return result.Task.WaitAsync(session!.Token);
    }
    protected override void Dispose(bool disposing){if(disposing){closing=true;Stop();}base.Dispose(disposing);}
}
